x-develop:
  services:
    web:
      watch:
        - path: ./apps/web
          target: /app
          action: sync
          ignore:
            - node_modules/
            - .git/
      urls:
        - "http://localhost:4321"
        - label: "PocketBase Admin"
          url: "http://localhost:8090/_/"

services:
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: {{name}}-web
    ports:
      - "4321:4321"
    volumes:
      - ./apps/web:/app
      - web_node_modules:/app/node_modules
    environment:
      - POCKETBASE_URL=http://pocketbase:8090
      - NODE_ENV=development
    depends_on:
      - pocketbase

  pocketbase:
    build:
      context: ./apps/pb
      dockerfile: Dockerfile
    container_name: {{name}}-pocketbase
    ports:
      - "8090:8090"
    volumes:
      - {{name}}_pb_data:/pb/pb_data
    environment:
      - NODE_ENV=development
      - SUPERUSER_EMAIL=${SUPERUSER_EMAIL}
      - SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD}
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  {{name}}_pb_data:
    name: {{name}}_pb_data
  web_node_modules:
    name: web_node_modules
