services:
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: {{sanitizedName}}-web
    ports:
      - "4321:4321"
    volumes:
      - ./apps/web:/app
      - {{sanitizedName}}_node_modules:/app/node_modules
    environment:
      - POCKETBASE_URL=http://pb:8090
      - NODE_ENV=development
    command: >
      sh -c "bun install && bun run dev"
    env_file:
      - ./.env.development
    depends_on:
      pb:
        condition: service_healthy

  pb:
    build:
      context: ./apps/pb
      dockerfile: Dockerfile
    container_name: {{sanitizedName}}-pb
    ports:
      - "8090:8090"
    volumes:
      - {{sanitizedName}}_pb_data:/pb/pb_data
    env_file:
      - ./.env.development
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  {{sanitizedName}}_pb_data:
  {{sanitizedName}}_node_modules:
