app = "{{name}}"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile.prod"

[http_service]
  internal_port = 4321
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[env]
  POCKETBASE_URL = "https://{{name}}-pb.fly.dev"
  NODE_ENV = "production"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
